## Array

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [6]:
# you can easily create an array filled with 0s:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
print(np.arange(4))
print(np.arange(0, 10, 2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [10]:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove, and Sort

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [13]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [14]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [ ]:
# ndarray.ndim()
# ndarray.size()
# ndarray.shape()

In [16]:
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],
                         [[0, 1, 2, 3], [4, 5, 6, 7]],
                         [[0, 1, 2, 3], [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [17]:
array_example.ndim

3

In [18]:
array_example.size

24

In [19]:
array_example.shape

(3, 2, 4)

In [20]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [21]:
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

## Reshape

In [ ]:
# np.reshape()

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [28]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [ ]:
# np.newaxis
# np.expand_dims

In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [30]:
# You can use np.newaxis to add new axis:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [31]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [32]:
# for a column vector, You can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [33]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
# You can use np.expand_dims to add an axis at index position 1 with:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [35]:
# You can add an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [36]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [37]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [39]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [40]:
# You can select elements that are divisible by 2
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [41]:
# You can select elements that satisfy two conditions using the & and | operators
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [ ]:
# slicing indexing
# np.vstack()
# np.hstack()
# np.hsplit()
# .view()
# .copy()

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [43]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [44]:
a_1 = np.array([[1, 1],
               [2, 2]])

In [45]:
a_2 = np.array([[3, 3],
               [4, 4]])

In [46]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
# Or stack them horizontally with hstack
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [48]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [49]:
# If you wanted to split this array into three equally shape arrays
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [51]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
# You can create a new array object that looks at the same data
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
# Using the copy method will make a complete copy of the array its data (a deep copy).
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operations

In [54]:
a = np.array([1, 2, 3, 4])
# Add all of the elements in the array
a.sum()

10

In [55]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [56]:
# You can sum the rows
b.sum(axis=0)

array([3, 3])

In [57]:
# You can sum the columns
b.sum(axis=1)

array([2, 4])

In [58]:
data = np.array([1, 2])
data

array([1, 2])

In [59]:
ones = np.ones(2)
ones

array([1., 1.])

In [60]:
data + ones

array([2., 3.])

In [61]:
data * data

array([1, 4])

In [62]:
data / data

array([1., 1.])

## Broadcasting

In [63]:
data * 2

array([2, 4])

## More Array Operations

In [ ]:
# data.max()
# data.min()
# data.sum()

In [64]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [65]:
A.sum()

4.8595784

In [66]:
A.min()

0.05093587

In [67]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [68]:
A.max()

0.82485143

In [69]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [70]:
A.std()

0.21392120766089617

## Matrices

In [72]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.22952903, 0.39302743],
       [0.50410322, 0.24257068],
       [0.3675368 , 0.34867624]])

In [73]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.12516818 0.03879183]
 [0.31591471 0.81792189]
 [0.34890905 0.84717102]]


## Matrix Arithmetic

In [74]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [75]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [76]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [77]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [78]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [79]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [80]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [81]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [82]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [83]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [84]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [85]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [86]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [87]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [88]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
arr = np.arange(6).reshape(2, 3)
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [91]:
ndarr = np.array([[[1, 2], [3, 4],
                  [5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [92]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [93]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [94]:
print(np.random.random((4,3,2)))

[[[0.3626977  0.62516481]
  [0.39478435 0.82183941]
  [0.76023729 0.01351951]]

 [[0.35205042 0.18416477]
  [0.78439547 0.80488543]
  [0.85350675 0.9705508 ]]

 [[0.05565604 0.37706372]
  [0.49481597 0.57347301]
  [0.9580154  0.84008006]]

 [[0.08620292 0.24799854]
  [0.63005201 0.6271218 ]
  [0.8914265  0.87633199]]]


## Flatten N-Dimensional Array

In [95]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [96]:
# You can use flatten to flatten your array into a 1D array
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [ ]:
# error = (1/n) * np.sum(np.square(observed - prediction))