In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [5]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [6]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [7]:
mean_ = sum(x) / len(x)
mean_

8.7

In [8]:
mean_ = statistics.mean(x)
print(mean_)

8.7


In [9]:
mean_ = statistics.mean(x_with_nan)
print(mean_)

nan


In [10]:
mean_ = np.mean(y)
mean_

8.7

In [11]:
mean_ = y.mean()
mean_

8.7

In [12]:
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [13]:
np.nanmean(y_with_nan)

8.7

In [14]:
mean_ = z.mean()
mean_

8.7

In [15]:
z_with_nan.mean()

8.7

Rata-Rata Tertimbang

In [17]:
0.2*2+0.5*4+0.3*8

4.8

In [19]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
print(wmean)

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
print(wmean)

6.95
6.95


In [20]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

6.95
6.95


In [21]:
(w * y).sum() / w.sum()

6.95

Arti Harmonik

In [22]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [23]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [24]:
scipy.stats.hmean(z)

2.7613412228796843

Rata-Rata Geometris

In [25]:
gmean = 1
for item in x:
    gmean *= item
    
gmean **= 1 / len(x)
gmean

4.677885674856041

In [26]:
scipy.stats.gmean(y)

4.67788567485604

In [27]:
scipy.stats.gmean(z)

4.67788567485604

Median

In [32]:
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])
    
median_

4

In [33]:
x

[8.0, 1, 2.5, 4, 28.0]

In [34]:
statistics.median_low(x[:-1])

2.5

In [35]:
statistics.median_high(x[:-1])

4

In [36]:
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

6.0
4
8.0


In [37]:
median_ = np.median(y)
print(median_)

4.0


In [38]:
median_ = np.median(y[:-1])
print(median_)

3.25


Mode

In [43]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]
mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [44]:
mode_ = statistics.mode(u)
mode_

2

In [45]:
u, v = np.array(u), np.array(v)

mode_ = scipy.stats.mode(u)
mode_

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9920\3259432411.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_ = scipy.stats.mode(u)


ModeResult(mode=array([2]), count=array([2]))

In [46]:
mode_ = scipy.stats.mode(v)
mode_

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9920\4273125489.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_ = scipy.stats.mode(v)


ModeResult(mode=array([12]), count=array([3]))

In [47]:
print(mode_.mode)
print(mode_.count)

[12]
[3]


In [49]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

print(u.mode())
print(v.mode())
print(w.mode())

0    2
dtype: int32
0    12
1    15
dtype: int32
0    2.0
dtype: float64


Ukuran Variabilitas

In [51]:
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

In [52]:
var_ = statistics.variance(x)
var_

123.2

In [53]:
var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [55]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [56]:
z.var(ddof=1)

123.19999999999999

Standar Deviasi

In [58]:
std_ = var_ ** 0.5
std_

11.099549540409285

In [59]:
std_ = statistics.stdev(x)
std_

11.099549540409287

In [60]:
np.std(y, ddof=1)

11.099549540409285

In [61]:
y.std(ddof=1)

11.099549540409285

In [62]:
np.nanstd(y_with_nan, ddof=1)

11.099549540409285

In [63]:
z.std()

11.099549540409285

Kecondongan (Skewness)

In [66]:
x = [8.0, 1, 2.5, 4, 28.0]
n = len(x)

mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))
skew_

1.9470432273905929

In [67]:
y, y_with_nan = np.array(x), np.array(x_with_nan)

scipy.stats.skew(y, bias=False)

1.9470432273905927

In [68]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [69]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

z.skew()

1.9470432273905924

In [70]:
z_with_nan.skew()

1.9470432273905924

Persentil

In [73]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [74]:
statistics.quantiles(x, n=2)

[8.0]

In [75]:
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [77]:
y = np.array(x)
print(np.percentile(y, 5))
np.percentile(y, 95)

-3.44


34.919999999999995

In [78]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [81]:
np.median(y)

8.0

In [80]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [82]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [83]:
np.quantile(y, 0.05)

-3.44

In [84]:
np.quantile(y, 0.95)

34.919999999999995

In [85]:
np.quantile(y, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [86]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [87]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)
z.quantile(0.05)

-3.44

In [88]:
z.quantile(0.95)

34.919999999999995

In [89]:
z.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [90]:
z_with_nan.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

Rentang

In [91]:
np.ptp(y)

46.0

In [92]:
np.ptp(z)

46.0

In [94]:
np.ptp(y_with_nan)

nan

In [95]:
np.ptp(z_with_nan)

nan

In [96]:
np.amax(y) - np.amin(y)

46.0

In [97]:
np.nanmax(y_with_nan) - np.nanmin(y_with_nan)

46.0

In [98]:
y.max() - y.min()

46.0

In [99]:
z.max() - z.min()

46.0

In [100]:
z_with_nan.max() - z_with_nan.min()

46.0

Rentang Interkuartil

In [101]:
quartiles = np.quantile(y, [0.25, 0.75])
quartiles[1] - quartiles[0]

20.9

In [103]:
quartiles = z.quantile([0.25, 0.75])
quartiles[0.75] - quartiles[0.25]

20.9

Ringkasan Statistik Deskriptif

In [104]:
result = scipy.stats.describe(y, ddof=1, bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [105]:
result.nobs

9

In [107]:
result.minmax[0] # Min

-5.0

In [108]:
result.minmax[1] # Max

41.0

In [109]:
result.mean

11.622222222222222

In [110]:
result.variance

228.75194444444446

In [111]:
result.skewness

0.9249043136685094

In [112]:
result.kurtosis

0.14770623629658886

In [113]:
result = z.describe()
result

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

In [114]:
result['mean']

11.622222222222222

In [115]:
result['std']

15.12454774346805

In [116]:
result['min']

-5.0

In [117]:
result['max']

41.0

In [118]:
result['25%']

0.1

In [119]:
result['50%']

8.0

In [121]:
result['75%']

21.0

Ukuran Korelasi Antar Pasangan Data

In [122]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x_), pd.Series(y_)

Kovarian

In [124]:
n = len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range (n))... / (n - 1))
cov_xy

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3386532289.py, line 3)