## List

In [1]:
my_list = [1, 2, 3]

In [2]:
print(my_list)

[1, 2, 3]


In [3]:
my_list + [4, 5]

[1, 2, 3, 4, 5]

In [4]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


In [5]:
my_list.append(4)

In [6]:
print(my_list)

[1, 2, 3, 4]


In [7]:
my_list.append([4, 5])

In [8]:
print(my_list)

[1, 2, 3, 4, [4, 5]]


In [9]:
mylist = [1, 2, 3]

In [10]:
print(mylist)

[1, 2, 3]


In [11]:
mylist.extend([4, 5, 6])

In [12]:
print(mylist)

[1, 2, 3, 4, 5, 6]


In [13]:
mylist.remove(4)

In [14]:
print(mylist)

[1, 2, 3, 5, 6]


In [15]:
print(my_list)

[1, 2, 3, 4, [4, 5]]


In [16]:
my_list.remove([4, 5])

In [17]:
print(my_list)

[1, 2, 3, 4]


## Dictionaries

In [18]:
student = {}

In [19]:
student = {'name': 'Ishma', 'age': '17'}

In [20]:
employee = {'cto': {'name': 'ishma', 'age': '17'}}

In [21]:
student = dict(name='Billy', age=38)

In [22]:
print(student['name'])

Billy


In [23]:
print(student['age'])

38


In [24]:
print(student)

{'name': 'Billy', 'age': 38}


In [25]:
del student['age']

In [26]:
print(student)

{'name': 'Billy'}


In [27]:
student = {'name': 'Ishma', 'age': '17'}

In [28]:
print(student.keys())

dict_keys(['name', 'age'])


In [29]:
print(student.values())

dict_values(['Ishma', '17'])


## Tuples

In [30]:
people = ('Ishma', ('kode', 'random'))

In [31]:
print(people)

('Ishma', ('kode', 'random'))


In [32]:
print(people[0])

Ishma


In [33]:
print(people[1])

('kode', 'random')


In [34]:
print(people[1][0])

kode


In [35]:
numbers = (1, 2, 3, 4)

In [36]:
new_numbers = numbers[0], numbers[1:3]

In [37]:
print(new_numbers)

(1, (2, 3))


In [38]:
print(numbers)

(1, 2, 3, 4)


In [39]:
email_attr = ('to', 'from', 'cc', 'bcc', 'subject', 'body')

In [40]:
email_attr_list = list(email_attr)

In [41]:
email_attr_list.sort()

In [42]:
print(email_attr_list)

['bcc', 'body', 'cc', 'from', 'subject', 'to']


## Files

In [43]:
myfile = open('text.txt','w')

In [44]:
myfile.write('halo text file!\n')

16

In [45]:
myfile.write('selamat tinggal text file!\n')

27

In [46]:
myfile.close()

In [47]:
myfile = open('text.txt')

In [48]:
myfile.readline()

'halo text file!\n'

In [49]:
myfile.readline()

'selamat tinggal text file!\n'

In [50]:
open('text.txt').read()

'halo text file!\nselamat tinggal text file!\n'

In [51]:
print(open('text.txt').read())

halo text file!
selamat tinggal text file!



In [52]:
x, y, z = 43, 44, 45

In [53]:
message = 'Spam'

In [54]:
data = {'a': 1, 'b': 2}

In [55]:
list = [1, 2, 3]

In [56]:
file = open('text.txt', 'w')

In [57]:
file.write(message + '\n')

5

In [58]:
file.write('%s,%s,%s\n' % (x, y, z))

9

In [59]:
file.write(str(list) + '$' + str(data) + '\n')

27

In [60]:
file.close()

## While Loops

In [61]:
message = "spam"

In [62]:
while message != '':
    print(message, end=' ')
    message = message[1:]

spam pam am m 

In [63]:
a = 0
b = 13

In [64]:
while a < b:
    print(a, end=' ')
    a = a + 1

0 1 2 3 4 5 6 7 8 9 10 11 12 

while test:
    statements
    if test: break
    if test: continue
else:
    statements

In [65]:
while True:
    name = input('Enter name: ')
    if name == 'stop': break
    age = input('Enter age: ')
    print('Hello', name, '=>', int(age) ** 2)

Enter name: ishma
Enter age: 21
Hello ishma => 441
Enter name: rafi
Enter age: 17
Hello rafi => 289
Enter name: ulfa
Enter age: 8
Hello ulfa => 64
Enter name: sisi
Enter age: 2
Hello sisi => 4
Enter name: stop


## For While

In [66]:
for word in ['ishma', 'billy', 'kode']:
    print(word, end='\n')

ishma
billy
kode


In [67]:
sum = 0

In [68]:
for i in [1, 2, 3, 4]:
    sum = sum + i

In [69]:
sum

10

In [70]:
prod = 1

In [71]:
for item in [1, 2, 3, 4]: prod *= item

In [72]:
prod

24

In [73]:
text = 'foxy fox'

In [74]:
words = ('is', 'great', 'animal')

In [75]:
for chara in text: print(chara, end=' ')

f o x y   f o x 

In [76]:
for word in words: print(word, end='...')

is...great...animal...

In [77]:
coor = [(1, 2),(3, 4),(5, 6)]

In [78]:
for (x,y) in coor: print(x,y)

1 2
3 4
5 6


In [79]:
x = 0
while (x < 100):
    x+=2
    print(x)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [81]:
for l in 'Idaz':
    if l == 'a':
        pass
    print(l, end=", ")

I, d, a, z, 

## If Statements

In [ ]:
if kondisi1:
    blok kode1
elif kondisi2:
    blok kode2
else:
    blok kode3

In [82]:
if 1:
    print('true')

true


In [83]:
if not 1:
    print('true')
else:
    print('false')

false


In [84]:
age = input('Enter your age: ')
if int(age) * 365 > 20000:
    print('Time to retire!')
elif int(age) * 365 > 10000:
    print('Lots of time left!')
else:
    print('Time to get started!')

Enter your age: 36
Lots of time left!


In [85]:
age = input('Enter your age: ')
if int(age) * 365 > 20000:
    print('Time to retire!')
elif int(age) * 365 > 10000:
    print('Lots of time left!')
else:
    print('Time to get started!')

Enter your age: 45
Lots of time left!


In [86]:
age = input('Enter your age: ')
if int(age) * 365 > 20000:
    print('Time to retire!')
elif int(age) * 365 > 10000:
    print('Lots of time left!')
else:
    print('Time to get started!')

Enter your age: 78
Time to retire!


In [87]:
age = input('Enter your age: ')
if int(age) * 365 > 20000:
    print('Time to retire!')
elif int(age) * 365 > 10000:
    print('Lots of time left!')
else:
    print('Time to get started!')

Enter your age: 100
Time to retire!


In [89]:
age = input('Enter your age: ')
if int(age) * 365 > 20000:
    print('Time to retire!')
elif int(age) * 365 > 10000:
    print('Lots of time left!')
else:
    print('Time to get started!')

Enter your age: 17
Time to get started!


In [90]:
user_age = input('Enter your age: ')
age = int(user_age) * 365

if age >= 9490:
    print('You are a Jedi Master now. Go learn from Master Yoda!!')
elif age >= 8395 and age < 9490:
    print('Becoming Jedi Knight')
else:
    print('You are a young Padawan')

Enter your age: 33
You are a Jedi Master now. Go learn from Master Yoda!!


In [91]:
user_age = input('Enter your age: ')
age = int(user_age) * 365

if age >= 9490:
    print('You are a Jedi Master now. Go learn from Master Yoda!!')
elif age >= 8395 and age < 9490:
    print('Becoming Jedi Knight')
else:
    print('You are a young Padawan')

Enter your age: 23
Becoming Jedi Knight


In [92]:
user_age = input('Enter your age: ')
age = int(user_age) * 365

if age >= 9490:
    print('You are a Jedi Master now. Go learn from Master Yoda!!')
elif age >= 8395 and age < 9490:
    print('Becoming Jedi Knight')
else:
    print('You are a young Padawan')

Enter your age: 17
You are a young Padawan


In [95]:
X = 10
Y = 50
if (X ** 2 > 100 and Y < 100):
    print(X, Y)

## Functions

In [ ]:
# def funcname(self, parameter_list):
#    pass

In [1]:
def add(a, b):
    return a + b

In [2]:
add(5, 4)

9

In [3]:
add_things = add(10, 4)

In [4]:
print(add_things)

14


In [5]:
def add_and_print(a, b):
    print(a + b)

In [6]:
add_and_print(1, 3)

4


In [7]:
x = add_and_print(5, 3)

8


In [8]:
print(x)

None


In [9]:
def intersection(first_word, second_word):
    result = []
    for x in first_word:
        if x in second_word:
            result.append(x)
    return result

In [10]:
word1 = 'spam'
word2 = 'scam'
char_of_intersect = intersection(word1, word2)
print(char_of_intersect)

['s', 'a', 'm']


## Modules & Built-in Function

In [11]:
print(abs(-123))

123


In [12]:
print(abs(123))

123


In [13]:
numbers = [1, 2, 3]
print(isinstance(numbers, list))

True


In [14]:
print(isinstance(numbers, dict))

False


In [17]:
number = 22
print(isinstance(number, dict))

False


In [18]:
print(isinstance(number, list))

False


In [19]:
print(isinstance(number, int))

True


In [20]:
numbers = [1, 2, 3, 4, 5, 6]

In [21]:
print(max(numbers))

6


In [22]:
print(min(numbers))

1


In [23]:
alphas = ['a', 'b', 'z']
print(max(alphas))

z


In [24]:
print(min(alphas))

a


In [ ]:
# index = memberikan informasi dari suatu item berada dalam sebuah list

In [25]:
languages = ['py', 'js', 'go', 'c']

In [26]:
print(languages.index('go'))

2


In [27]:
languages.sort()

In [28]:
print(languages)

['c', 'go', 'js', 'py']


In [29]:
name = 'ishma'

In [30]:
print(name)

ishma


In [31]:
name.replace('a', 'i')

'ishmi'

In [32]:
name.capitalize()

'Ishma'

In [ ]:
# Modules
# import = untuk mengambil keseluruhan modul
# from = hanya mengambil sebagian modul

## Packages

## NumPy

In [35]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [36]:
!pip install numpy

In [37]:
import numpy as np

In [38]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]

In [39]:
weight = [66.4, 49.22, 66.3, 88.56, 65.4]

In [40]:
np_height = np.array(height)
np_weight = np.array(weight)

In [41]:
bmi = np_weight/np_height ** 2

In [42]:
print(bmi)

[21.68163265 17.43905896 20.46296296 27.03214188 22.8983579 ]


In [43]:
mixed_array = np.array([1.0, 'is', True])
print(mixed_array)

['1.0' 'is' 'True']


In [44]:
numlist = [1, 2, 3]
nparray = np.array([1, 2, 3])

In [45]:
numlist + numlist

[1, 2, 3, 1, 2, 3]

In [46]:
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [47]:
bmi > 24

array([False, False, False,  True, False])

In [48]:
bmi[bmi > 24]

array([27.03214188])

## Statistik Dasar dengan Numpy

In [49]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)

In [50]:
height

array([1.56, 1.84, 1.62, ..., 1.25, 1.67, 1.85])

In [51]:
len(height)

5000

In [52]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [53]:
weight

array([51.83, 52.46, 59.12, ..., 74.4 , 67.94, 37.87])

In [54]:
len(weight)

5000

In [55]:
np_city = np.column_stack((height, weight))

In [56]:
np.mean(np_city[:,0])

1.74288

In [57]:
np.median(np_city[:,0])

1.74

In [58]:
np.std(np_city[:,0])

0.1986589680834973

## Numpy Array 2D

In [62]:
height = np.array([1.75, 1.68, 1.8])

In [63]:
weight = np.array([66.4, 49.22, 66.3])

In [64]:
type(height)

numpy.ndarray

In [65]:
np_2d = np.array([[1.75, 1.68, 1.8],
                 [66.4, 49.22, 66.3]])

In [66]:
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

In [67]:
np_2d.shape

(2, 3)

In [68]:
np_2d[0]

array([1.75, 1.68, 1.8 ])

In [69]:
np_2d[0][2]

1.8

In [70]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [71]:
np_2d[1,:]

array([66.4 , 49.22, 66.3 ])